Src/stm32f4xx_hal_msp.c File Reference
#include `stm32f4xx_hal.h`
Functions
void _Error_Handler (char *, int)
This function is executed in case of error occurrence.
void HAL_MspInit (void)
void HAL_ADC_MspInit (ADC_HandleTypeDef *hadc)
void HAL_ADC_MspDeInit (ADC_HandleTypeDef *hadc)
void HAL_TIM_Base_MspInit (TIM_HandleTypeDef *htim_base)
void HAL_TIM_MspPostInit (TIM_HandleTypeDef *htim)
void HAL_TIM_Base_MspDeInit (TIM_HandleTypeDef *htim_base)
void HAL_UART_MspInit (UART_HandleTypeDef *huart)
void HAL_UART_MspDeInit (UART_HandleTypeDef *huart)
Variables
DMA_HandleTypeDef hdma_adc1
Function Documentation
_Error_Handler()
void _Error_Handler (char * file, int line)
This function is executed in case of error occurrence.
Parameters
file The file name as string.
line The line in file as a number.
Return values
None
Definition at line 1010 of file main.c.
Referenced by HAL_ADC_MspInit(), and SystemClock_Config().
HAL_ADC_MspDeInit()
void HAL_ADC_MspDeInit (ADC_HandleTypeDef * hadc)
ADC1 GPIO Configuration PA4 ------> ADC1_IN4
Definition at line 139 of file stm32f4xx_hal_msp.c.
HAL_ADC_MspInit()
void HAL_ADC_MspInit (ADC_HandleTypeDef * hadc)
ADC1 GPIO Configuration PA4 ------> ADC1_IN4
Definition at line 90 of file stm32f4xx_hal_msp.c.
References _Error_Handler(), and hdma_adc1.
HAL_MspInit()
void HAL_MspInit (void)
Initializes the Global MSP.
Definition at line 61 of file stm32f4xx_hal_msp.c.
HAL_TIM_Base_MspDeInit()
void HAL_TIM_Base_MspDeInit (TIM_HandleTypeDef * htim_base)
TIM1 GPIO Configuration PA8 ------> TIM1_CH1
TIM2 GPIO Configuration PA0-WKUP ------> TIM2_CH1 PA1 ------> TIM2_CH2
TIM4 GPIO Configuration PB6 ------> TIM4_CH1
Definition at line 284 of file stm32f4xx_hal_msp.c.
HAL_TIM_Base_MspInit()
void HAL_TIM_Base_MspInit (TIM_HandleTypeDef * htim_base)
TIM1 GPIO Configuration PA8 ------> TIM1_CH1
TIM2 GPIO Configuration PA1 ------> TIM2_CH2
TIM4 GPIO Configuration PB6 ------> TIM4_CH1
Definition at line 167 of file stm32f4xx_hal_msp.c.
HAL_TIM_MspPostInit()
void HAL_TIM_MspPostInit (TIM_HandleTypeDef * htim)
TIM2 GPIO Configuration PA0-WKUP ------> TIM2_CH1
Definition at line 257 of file stm32f4xx_hal_msp.c.
HAL_UART_MspDeInit()
void HAL_UART_MspDeInit (UART_HandleTypeDef * huart)
USART2 GPIO Configuration PA2 ------> USART2_TX PA3 ------> USART2_RX
Definition at line 390 of file stm32f4xx_hal_msp.c.
HAL_UART_MspInit()
void HAL_UART_MspInit (UART_HandleTypeDef * huart)
USART2 GPIO Configuration PA2 ------> USART2_TX PA3 ------> USART2_RX
Definition at line 357 of file stm32f4xx_hal_msp.c.
Variable Documentation
hdma_adc1
DMA_HandleTypeDef hdma_adc1
File Name : stm32f4xx_hal_msp.c Description : This file provides code for the MSP Initialization and de-Initialization codes.
This notice applies to any and all portions of this file that are not between comment pairs USER CODE BEGIN and USER CODE END. Other portions of this file, whether inserted by the user or by software development tools are owned by their respective copyright owners.
Copyright (c) 2018 STMicroelectronics International N.V. All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted, provided that the following conditions are met:
Redistribution of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of STMicroelectronics nor the names of other contributors to this software may be used to endorse or promote products derived from this software without specific written permission.
This software, including modifications and/or derivative works of this software, must execute solely and exclusively on microcontroller or microprocessor devices manufactured by or for STMicroelectronics.
Redistribution and use of this software other than as permitted under this license is void and will automatically terminate your rights under this license.
THIS SOFTWARE IS PROVIDED BY STMICROELECTRONICS AND CONTRIBUTORS `AS IS` AND ANY EXPRESS, IMPLIED OR STATUTORY WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT OF THIRD PARTY INTELLECTUAL PROPERTY RIGHTS ARE DISCLAIMED TO THE FULLEST EXTENT PERMITTED BY LAW. IN NO EVENT SHALL STMICROELECTRONICS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition at line 61 of file main.c.
Referenced by HAL_ADC_MspInit().